### ISSUE TITLE
Add possibility to define squawk ranges

### ISSUE THREAD

**Issue by jannikvogel** [pole95/ESSquawks#1]
Hi!

Would save a lot of work to add a possibility to define squawk ranges instead of each individual squawk code within that range.

Could be: 
```
"codestart": "7004",
"codeend": "7026",
```

**Comment by pole95** [comment]
Integrated in v1.0.1, instead of defining "code", you define "range" as follows:
```json
"range" : {
  "start" : "7004",
  "end" : "7026"
}
```
